#+STARTUP: beamer
#+LaTeX_CLASS: beamer
#+LaTeX_CLASS_OPTIONS: [9pt]

#+latex_header: \mode<beamer>{\usetheme{Warsaw}}
#+latex_header: \mode<beamer>{\setbeamertemplate{blocks}[rounded][shadow=false]}
#+latex_header: \mode<beamer>{\addtobeamertemplate{block begin}{\pgfsetfillopacity{0.8}}{\pgfsetfillopacity{1}}}
#+latex_header: \mode<beamer>{\setbeamercolor{structure}{fg=orange}}
#+latex_header: \mode<beamer>{\setbeamercovered{transparent}}
#+latex_header: \AtBeginSection[]{\begin{frame}<beamer>\frametitle{Topic}\tableofcontents[currentsection]\end{frame}}

#+latex_header: \usepackage{subcaption}
#+latex_header: \usepackage{multimedia}
#+latex_header: \usepackage{tikz}
#+latex_header: \usepackage{subfigure,subfigmat}
#+latex_header: \usepackage{threeparttable}
#+latex_header: \usetikzlibrary{shapes,arrows,shadows}
#+latex_header: \usepackage{bm, amssymb, amsmath, array, pdfpages,graphicx}

#+begin_latex
% Define my settings

\graphicspath{{../Figures/}}
% Add Princeton shield logo
\addtobeamertemplate{frametitle}{}{%
\begin{tikzpicture}[remember picture,overlay]
\node[anchor=north east,yshift=2pt] at (current page.north east) {\includegraphics[height=0.7cm]{Shield}};
\end{tikzpicture}}
%
#+end_latex

#+latex_header: \newcommand{\bv}[1]{\mathbf{#1}}
#+latex_header: \newcommand{\diff}[2]{\frac{\partial #1}{\partial #2}}
#+latex_header: \newcommand{\beq}[0]{\begin{equation}}
#+latex_header: \newcommand{\eeq}[0]{\end{equation}}
#+latex_header: \newcommand{\beqa}[0]{\begin{eqnarray}}
#+latex_header: \newcommand{\eeqa}[0]{\end{eqnarray}}
#+latex_header: \newcommand{\beqq}[0]{\begin{equation*}}
#+latex_header: \newcommand{\eeqq}[0]{\end{equation*}}
#+latex_header: \newcommand{\bs}[1]{\boldsymbol{#1}}
#+latex_header: \newcommand{\ip}[2]{\langle #1, #2\rangle}
#+BEAMER_FRAME_LEVEL: 2

#+DATE: APS 68$^{th}$ Annual DFD Meeting \\ Boston, MA \\ November 2015
#+TITLE: Uncertainty Quantification of Low-Dimensional Models
#+AUTHOR: Anthony DeGennaro \newline Scott Dawson \newline Clarence W. Rowley III \newline Princeton University
\institute{Princeton University}


* Introduction
** Motivation
- Many fluid systems have uncertainties associated with them
  - Governing parameters
  - Boundary conditions
- Wing icing [fn:Broeren][fn:Addy]
  - Ice shape on leading edge of airfoil varies with physical conditions
#+begin_latex
\begin{figure}[ht]
\centering
\includegraphics[width=0.7\textwidth]{SampleIceShapes} \\
\textbf{Broeren, 2013}
\end{figure}
#+end_latex
[fn:Broeren] Broeren et. al. /Swept-Wing Ice Accretion Characterization and Aerodynamics/. AIAA 2013-2824.
[fn:Addy] Addy, H. E. /Ice Accretions and Icing Effects for Modern Airfoils/. NASA TP 2000-210031.

** Motivation
- Many fluid systems have uncertainties associated with them
  - Governing parameters
  - Boundary conditions
- Airplane cargo hold fires [fn:DeGennaro]
  - Fire source location, temperature can be uncertain
#+begin_latex
\begin{figure}[ht]
\centering
\begin{minipage}[b]{0.45\linewidth}
\movie[width=0.9\textwidth,height=0.66\textwidth,poster,autostart,loop,borderwidth]{}{FireColdCenter.avi} \\
\centering
\textbf{Colder Source} \\
\end{minipage}
\begin{minipage}[b]{0.45\linewidth}
\movie[width=0.9\textwidth,height=0.66\textwidth,poster,autostart,loop,borderwidth]{}{FireHotCenter.avi} \\
\centering
\textbf{Hotter Source}
\end{minipage}
\end{figure}
#+end_latex

[fn:DeGennaro] DeGennaro, Lohry et. al. /Uncertainty Quantification for Cargo Hold Fires/. To appear at AIAA Scitech 2016.
** Motivation
*Goal: apply uncertainty quantification tools to low-dimensional models*
  - Investigate statistical variations in spatial structures and dynamics
    - POD modes, DMD modes
    - DMD eigenvalues
*Potential applications*
 - Develop low-dimensional models accurate for range of parameter uncertainty
 - POD Galerkin models
    - Sensitive to parametric variation/uncertainty


* Background
** Low-Dimensional Modeling
- Proper Orthogonal Decomposition (POD)
  - Data compression, dominant spatial features
  - Modes are eigenvectors of the dataset covariance matrix
  - Modes describe dataset better than any other linear basis
- Dynamic Mode Decomposition (DMD)
  - Describe dataset as linear dynamical system
  - Spatial modes + (frequencies, growth/decay rates)
#+begin_latex
%\begin{columns}[c]
%\column{0.5\textwidth}
%   \centering
%    \textbf{Cylinder, Re = 100}
%    \movie[width=0.9\textwidth,height=0.3\textwidth,poster,autostart,loop,borderwidth]{}{CylinderRe100.mp4}
%\column{0.5\textwidth}
%   \centering
%    \textbf{POD/DMD Modes} \\
%    \includegraphics[width=0.9\textwidth]{CylinderRe100POD1} \\
%    \includegraphics[width=0.9\textwidth]{CylinderRe100POD2}
%\end{columns}



\fontsize{9}\selectfont
% Define the layers to draw the diagram
\pgfdeclarelayer{background}
\pgfdeclarelayer{foreground}
\pgfsetlayers{background,main,foreground}

% Define block styles used later

\tikzstyle{basic}=[draw, fill=blue!20, text width=5em, 
    text centered, minimum height=2.5em,drop shadow]
\tikzstyle{mode} = [basic, text width=10em, fill=blue!20, 
    minimum height=4em, rounded corners, drop shadow]

% Define distances for bordering
\def\blockdist{2.3}
\def\edgedist{2.5}
\centering
\begin{tikzpicture}
    \node (Simulation) [mode]  {\movie[width=0.9\textwidth,height=0.3\textwidth,poster,autostart,loop,borderwidth]{}{CylinderRe100.mp4}\\[1em]\textbf{Cylinder: Re = 100}};
    \path (Simulation)+(4,0) node (POD1) [mode] {\includegraphics[width=0.9\textwidth]{CylinderRe100POD1}\\[1em] \includegraphics[width=0.9\textwidth]{CylinderRe100POD2}\\[1em]\textbf{POD/DMD Modes}};

    \path [draw, ->, thick] (Simulation.east) |- node [right] {} (POD1.west);

\end{tikzpicture}
#+end_latex

** Polynomial Chaos Expansions (PCE)
- Polynomial Chaos Expansions (PCE)
  - Method for quantifying parametric uncertainty efficiently
  - Spectral method in probability space
  - Expand output in terms of basis polynomial functions of random variables
#+begin_latex
\begin{equation*}
\begin{aligned}
f(\xi) &\approx \sum_{i}^N a_i \psi_i(\xi) \\
\langle f , g \rangle &= \int_{\Gamma} f(\xi) g(\xi) \rho(\xi) d\xi \quad , \quad \langle \psi_i , \psi_j \rangle = \delta_{ij}
\end{aligned}
\end{equation}
\fontsize{9}\selectfont
% Define the layers to draw the diagram
\pgfdeclarelayer{background}
\pgfdeclarelayer{foreground}
\pgfsetlayers{background,main,foreground}

% Define block styles used later

\tikzstyle{sensor}=[draw, fill=blue!20, text width=5em, 
    text centered, minimum height=2.5em,drop shadow]
\tikzstyle{ann} = [above, text width=5em, text centered]
\tikzstyle{wa} = [sensor, text width=10em, fill=blue!20, 
    minimum height=7em, rounded corners, drop shadow]

% Define distances for bordering
\def\blockdist{2.3}
\def\edgedist{2.5}

\begin{tikzpicture}
    \node (CleanAirfoil) [wa]  {\includegraphics[width=0.9\textwidth]{ExamplePDF}\\\textbf{Input}};
    \path (CleanAirfoil)+(4,0) node (FlowSolver) [wa] {\textbf{Computation/}\\\textbf{Experiment}};
    \path (FlowSolver)+(4,0) node (Droplet) [wa] {\includegraphics[width=0.9\textwidth]{ExamplePDF2}\\\textbf{Output}};

    \path [draw, ->, thick] (CleanAirfoil.east) |- node [right] {} (FlowSolver.west);
    \path [draw, ->, thick] (FlowSolver.east) -- node [right] {} (Droplet.west);
            
\end{tikzpicture}

#+end_latex

** Polynomial Chaos Expansions (PCE)
#+begin_latex
\begin{figure}[ht]
\centering
\begin{minipage}[b]{0.45\linewidth}
\includegraphics[width=0.7\textwidth]{MonteCarlo} \\
\centering
\textbf{Monte Carlo} \\
\begin{equation*}
  y \approx \delta(\xi - \xi_k)
\end{equation} \\
\begin{itemize}
\item Draw random samples
\item Data exist at discrete points
\end{itemize}
\end{minipage}
\begin{minipage}[b]{0.45\linewidth}
\includegraphics[width=0.7\textwidth]{QuadraturePoints} \\
\centering
\textbf{Polynomial Chaos}
\begin{equation*}
  y \approx \sum_{i}^{Q} c_i \psi_i(\xi)
\end{equation} \\
\begin{itemize}
\item Take data at collocation points
\item Construct global surrogate
\end{itemize}
\end{minipage}
\end{figure}
#+end_latex


* Example: Cylinder Flow
** Setup
#+begin_latex
\begin{columns}[c]
\column{0.20\textwidth}
   \centering
    \includegraphics[width=1\textwidth]{CylinderPerturbations}   
\column{0.25\textwidth}
   \centering
    \textbf{Small Spike} \\
    \includegraphics[width=1\textwidth]{PerturbSmallHorn}
\column{0.25\textwidth}
   \centering
    \textbf{Medium Spike} \\
    \includegraphics[width=1\textwidth]{PerturbMediumHorn}
\column{0.25\textwidth}
   \centering
    \textbf{Large Spike} \\
    \includegraphics[width=1\textwidth]{PerturbBigHorn}
\end{columns}
#+end_latex
- Assume spike height is uniformly distributed between limits shown
- Re = 100
- Output = wake POD modes, DMD eigenvalues

** Methodology
# *Quantify Uncertain Input*
# - Identify source of uncertainty
#   - Physical parameters (eg. Reynolds number)
#   - Boundary conditions
# - Write a probabilistic description of uncertainty (ie. PDF)
# *Explore Uncertain Parameter Space*
# - Utilize efficient sampling of probability space
#   - Quadrature nodes corresponding to a spectral basis
# - Collect simulation data using discrete points in probability space
#   - Immersed boundary projection method (IBPM) code
# *Quantify Uncertain Output*
# - Quantify uncertainty in outputs
#   - POD modes
#   - DMD modes
#   - DMD eigenvalues

#+begin_latex
\fontsize{9}\selectfont
% Define the layers to draw the diagram
\pgfdeclarelayer{background}
\pgfdeclarelayer{foreground}
\pgfsetlayers{background,main,foreground}

% Define block styles used later

\tikzstyle{sensor}=[draw, fill=blue!20, text width=5em, 
    text centered, minimum height=2.5em,drop shadow]
\tikzstyle{ann} = [above, text width=5em, text centered]
\tikzstyle{wa} = [sensor, text width=10em, fill=blue!20, 
    minimum height=7em, rounded corners, drop shadow]

% Define distances for bordering
\def\blockdist{2.3}
\def\edgedist{2.5}

\begin{tikzpicture}
    \node (CleanAirfoil) [wa]  {\includegraphics[width=0.9\textwidth]{CylinderPerturbations}\\\vspace{0.25cm}\textbf{Spike Height}\\ $\xi = \mathcal{U}\lbrace 0,1\rbrace$};
    \path (CleanAirfoil)+(4,0) node (FlowSolver) [wa] {\textbf{Computation (IBPM)}\\\includegraphics[width=0.8\textwidth]{QuadraturePoints1D}};
    \path (FlowSolver)+(4,0) node (Droplet) [wa] {\includegraphics[width=0.9\textwidth]{POD2CompareInterp1}\\\vspace{0.25cm}\textbf{POD Modes}\\\vspace{0.2cm} $\phi(x,\xi) \approx \sum_i a_i(x) \psi_i(\xi)$};

    \path [draw, ->, thick] (CleanAirfoil.east) |- node [right] {} (FlowSolver.west);
    \path [draw, ->, thick] (FlowSolver.east) -- node [right] {} (Droplet.west);
            
\end{tikzpicture}

#+end_latex


** Range of Flow Behavior
#+begin_latex
\begin{columns}[c]
\column{0.5\textwidth}
   \centering
    \textbf{Cylinder, Re = 100}
    \movie[width=0.9\textwidth,height=0.3\textwidth,poster,autostart,loop,borderwidth]{}{CylinderRe100.mp4} \\
    \textbf{POD Modes} \\
    \includegraphics[width=0.9\textwidth]{CylinderRe100POD1} \\
    \includegraphics[width=0.9\textwidth]{CylinderRe100POD2} \\
    \includegraphics[width=0.9\textwidth]{CylinderRe100POD3}
\column{0.5\textwidth}
   \centering
    \textbf{Perturbed Cylinder, Re = 100}
    \movie[width=0.9\textwidth,height=0.3\textwidth,poster,autostart,loop,borderwidth]{}{PerturbCylinderRe100R1.mp4} \\
    \textbf{POD Modes} \\
    \includegraphics[width=0.9\textwidth]{PerturbRp95Re100POD1} \\
    \includegraphics[width=0.9\textwidth]{PerturbRp95Re100POD2} \\
    \includegraphics[width=0.9\textwidth]{PerturbRp95Re100POD3}
\end{columns}
#+end_latex
** Explore Parameter Space
#+begin_latex
\begin{columns}[c]
\column{0.5\textwidth}
\centering
\texbf{Height = 14$\%$}\\\vspace{-0.07cm}\includegraphics[width=0.95\textwidth]{POD2CompareInterp1} \\
\texbf{Height = 36$\%$}\\\vspace{-0.07cm}\includegraphics[width=0.95\textwidth]{POD2CompareInterp2} \\
\texbf{Height = 86$\%$}\\\vspace{-0.07cm}\includegraphics[width=0.95\textwidth]{POD2CompareInterp4}
\column{0.5\textwidth}
\centering
\texbf{Height = 14$\%$}\\\vspace{-0.07cm}\includegraphics[width=0.95\textwidth]{POD4CompareInterp1} \\
\texbf{Height = 36$\%$}\\\vspace{-0.07cm}\includegraphics[width=0.95\textwidth]{POD4CompareInterp2} \\
\texbf{Height = 86$\%$}\\\vspace{-0.07cm}\includegraphics[width=0.95\textwidth]{POD4CompareInterp4}
\end{columns}
#+end_latex
- Range from almost symmetric modes similar to cylinder to asymmetric perturbations
** Statistical Variance in Modes
#+begin_latex
\begin{columns}[c]
\column{0.5\textwidth}
\centering
\textbf{POD Mode 2} \\
\includegraphics[width=0.95\textwidth]{CylinderRe100POD2} \\
\textbf{Statistical Variance} \\
\includegraphics[width=0.95\textwidth]{VariancePOD2}
\column{0.5\textwidth}
\centering
\textbf{POD Mode 3} \\
\includegraphics[width=0.95\textwidth]{CylinderRe100POD3} \\
\textbf{Statistical Variance} \\
\includegraphics[width=0.95\textwidth]{VariancePOD3}
\end{columns}
#+end_latex
- Can statistically sample PCE surrogate
- Generate ensemble of cylinder spikes and associated POD modes
- Variance shows where POD modes are most affected by spike height

** Projection Error
- Choose the $Q-1$ points halfway between $Q$ quadrature nodes
- Calculate true modes and interpolated modes at $Q-1$ points
- Compare error between true modes and interpolated modes vs. true modes and mean modes

#+begin_latex
\begin{equation*}
N(Y) \equiv max(||Y(\xi_k) - \Phi(\xi_k)||_2) \quad , \quad k = 1...Q-1
\end{equation}
#+end_latex

|   | MODE | N(y_P) | N(\overline{y}) | N(\overline{y})/N(y_P) |
|---+------+--------+-----------------+------------------------|
| / |   <> |     <> |              <> |                        |
| # |    1 |   4e-3 |            3e-1 |                     75 |
| # |    2 |   3e-2 |            9e-1 |                     30 |
| # |    3 |   2e-1 |             1.2 |                      6 |
| # |    4 |   7e-1 |             1.5 |                      2 |
| # |    5 |   2e-1 |             1.8 |                      9 |
|---+------+--------+-----------------+------------------------|

- PCE model captures range of symmetrical to asymmetrical modes
** DMD Eigenvalues
#+begin_latex
\begin{columns}[c]
\column{0.3\textwidth}
   \centering
    \textbf{DMD Mode} \\
    \includegraphics[width=0.9\textwidth]{DMDMode1} \\
    \textbf{Frequency Distribution} \\
    \includegraphics[width=0.9\textwidth]{PerturbDMDEigSlowPDF}
\column{0.3\textwidth}
   \centering
    \textbf{DMD Mode} \\
    \includegraphics[width=0.9\textwidth]{DMDMode2} \\
    \textbf{Frequency Distribution} \\
    \includegraphics[width=0.9\textwidth]{PerturbDMDEigMediumPDF}
\column{0.3\textwidth}
   \centering
    \textbf{DMD Mode} \\
    \includegraphics[width=0.9\textwidth]{DMDMode3} \\
    \textbf{Frequency Distribution} \\
    \includegraphics[width=0.9\textwidth]{PerturbDMDEigFastPDF}
\end{columns}
#+end_latex

- Output is the imaginary part of DMD eigenvalues
- Histograms are based on 10,000 Monte Carlo samples of the PCE surrogate
- Modest deformation of uniform distribution for all frequencies
** Conclusions
- Uncertainty quantification techniques provide a fast, efficient, and
  accurate methodology for quantifying how low-dimensional models
  change with parametric uncertainty
  - POD modes
  - DMD modes/eigenvalues
- Further research
  - Multiple parameters
  - Apply to POD Galerkin models
